config/routes.rb
Rails.application.routes.draw do
  get 'splash/index'

  resources :about
  resources :products
  resources :contact

  root 'splash#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def new

  end

  def index

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def new

  end

  def index

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  http_basic_authenticate_with name: "admin", password: "password", except: [:index, :show]

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product
    else
      render 'new'
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to @product
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :dimension, :price)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/views/about/index.html.erb
<div class="container-fluid main_container d-flex" style="min-height: 100vh;">
  <div class="row border flex-fill">
    <div class="col h-100">

      <div class="row border" style="height: 30%; background-color: #20c997">
        <div class="col mh-100 justify-content-center align-self-center">
          <p class="mh-100 text-center" style="font-size: 10vh;">Company Name</p>
        </div>
      </div>

      <div class="row border" style="height: 20%; background-color: #20c997;">
        <div class="col">
          <%= link_to '<button type="button" class="btn btn-primary btn-block h-100" style="font-size: 8vh; opacity: .7; background-color: #008CBA;">Back</button>'.html_safe, controller:  'splash' %>
        </div>
      </div>

      <div class="row border" style="height: 40%; background-color: #20c997">
        <div class="col mh-100 justify-content-center align-self-center">
          <p class="mh-100 text-center" style="font-size: 10vh;">Demo website using Rails and Twitter Bootstrap!</p>
        </div>
      </div>

      <div class="row border" style="height: 10%; background-color: #20c997">
        <div class="col mh-100 justify-content-center align-self-center">
          <p class="text-center" style="font-size: 5vh;">Trademark Information - &#169; esoterickeys</p>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/contact/index.html.erb
<div class="container-fluid main_container d-flex" style="min-height: 100vh;">
  <div class="row border flex-fill">
    <div class="col h-100">

      <div class="row border" style="height: 30%; background-color: #20c997">
        <div class="col mh-100 justify-content-center align-self-center">
          <p class="mh-100 text-center" style="font-size: 10vh;">Company Name</p>
        </div>
      </div>

      <div class="row border" style="height: 20%; background-color: #20c997;">
        <div class="col">
          <%= link_to '<button type="button" class="btn btn-primary btn-block h-100" style="font-size: 8vh; opacity: .7; background-color: #008CBA;">Back</button>'.html_safe, controller:  'splash' %>
        </div>
      </div>

      <div class="row border" style="height: 40%; background-color: #20c997">
        <div class="col mh-100 justify-content-center align-self-center">
          <p class="mh-100 text-center" style="font-size: 10vh;">Contact system admin at - sectorten@gmail.com</p>
        </div>
      </div>

      <div class="row border" style="height: 10%; background-color: #20c997">
        <div class="col mh-100 justify-content-center align-self-center">
          <p class="text-center" style="font-size: 5vh;">Trademark Information - &#169; esoterickeys</p>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoTmp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<div class="container-fluid main_container d-flex" style="min-height: 100vh;">
  <div class="row border flex-fill">
    <div class="col h-100">

      <div class="row border" style="height: 25%; background-color: #20c997">
        <div class="col mh-100 justify-content-center align-self-center">
          <p class="mh-100 text-center" style="font-size: 10vh;">Edit <%= @product.name %></p>
        </div>
      </div>

      <div class="row border" style="height: 15%; background-color: #20c997;">
        <div class="col">
          <%= link_to '<button type="button" class="btn btn-primary btn-block h-100" style="font-size: 8vh; opacity: .7; background-color: #008CBA;">Back</button>'.html_safe, controller:  'products' %>
        </div>
      </div>

      <%= form_with model: @product, local: true do |form| %>
        <div class="row border" style="height: 15%; background-color: #d9d9d9;">
          <div class="col">
            <p class="text-right" style="font-size: 6vh;">
              <%= form.label :name %>
            </p>
          </div>

          <div class="col-10">
            <p class="h-100">
              <%= form.text_field :name, :class => 'w-100 h-100 mh-100', :style => 'font-size: 6vh;' %>
            </p>
          </div>
        </div>

        <div class="row border" style="height: 15%; background-color: #d9d9d9;">
          <div class="col">
            <p class="text-right" style="font-size: 6vh;">
              <%= form.label :dimension %>
            </p>
          </div>

          <div class="col-10">
            <p class="h-100">
              <%= form.text_field :dimension, :class => 'w-100 h-100 mh-100', :style => 'font-size: 6vh;' %>
            </p>
          </div>
        </div>

        <div class="row border" style="height: 15%; background-color: #d9d9d9;">
          <div class="col">
            <p class="text-right" style="font-size: 6vh;">
              <%= form.label :price %>
            </p>
          </div>

          <div class="col-10">
            <p class="h-100">
              <%= form.text_field :price, :class => 'w-100 h-100 mh-100', :style => 'font-size: 6vh;' %>
            </p>
          </div>
        </div>

        <div class="row border" style="height: 15%; background-color: #20c997;">
          <div class="col">
            <%= form.submit 'Edit', :class => 'btn btn-primary btn-block h-100', :style => 'font-size: 8vh; opacity: .7; background-color: #008CBA;' %>
          </div>
        </div>
      <% end %>

      <div class="row border" style="height: 10%; background-color: #20c997">
        <div class="col mh-100 justify-content-center align-self-center">
          <p class="text-center" style="font-size: 5vh;">Trademark Information - &#169; esoterickeys</p>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="container-fluid main_container d-flex" style="min-height: 100vh;">
  <div class="row border flex-fill">
    <div class="col h-100">

      <div class="row border" style="height: 25%; background-color: #20c997">
        <div class="col mh-100 justify-content-center align-self-center">
          <p class="mh-100 text-center" style="font-size: 10vh;">Company Name</p>
        </div>
      </div>

      <div class="row border" style="height: 15%; background-color: #20c997;">
        <div class="col">
          <%= link_to '<button type="button" class="btn btn-primary btn-block h-100" style="font-size: 8vh; opacity: .7; background-color: #008CBA;">Back</button>'.html_safe, controller:  'splash' %>
        </div>
      </div>

      <div class="row border" style="height: 10%; background-color: #20c997;">
        <div class="col">
      <%= link_to '<button type="button" class="btn btn-primary btn-block h-100" style="font-size: 5vh; opacity: .9; color: black; background-color: #d9d9d9;">New Product</button>'.html_safe, new_product_path %>
        </div>
      </div>

      <div class="row border" style="height: 40%;">
        <div class="table-responsive mh-100">
          <table class="table table-striped">
            <tr>
              <th class="col-4">Product</th>
              <th class="col-3">Dimension</th>
              <th class="col-3">Price</th>
              <th class="col">Options</th>
            </tr>
            <% @products.each do |product| %>
              <tr>
                <td style="font-size: 5vh;"><%= product.name %></td>
                <td style="font-size: 5vh;"><%= product.dimension %></td>
                <td style="font-size: 5vh;"><%= product.price %></td>
                <td style="font-size: 2vh;"><%= link_to 'Details', product_path(product) %><br><%= link_to 'Update', edit_product_path(product) %><br><%= link_to 'Remove', product_path(product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </table>
        </div>
      </div>

      <div class="row border" style="height: 10%; background-color: #20c997">
        <div class="col mh-100 justify-content-center align-self-center">
          <p class="text-center" style="font-size: 5vh;">Trademark Information - &#169; esoterickeys</p>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="container-fluid main_container d-flex" style="min-height: 100vh;">
  <div class="row border flex-fill">
    <div class="col h-100">

      <div class="row border" style="height: 25%; background-color: #20c997">
        <div class="col mh-100 justify-content-center align-self-center">
          <p class="mh-100 text-center" style="font-size: 10vh;">Create New Product</p>
        </div>
      </div>

      <div class="row border" style="height: 15%; background-color: #20c997;">
        <div class="col">
          <%= link_to '<button type="button" class="btn btn-primary btn-block h-100" style="font-size: 8vh; opacity: .7; background-color: #008CBA;">Back</button>'.html_safe, controller:  'products' %>
        </div>
      </div>

      <%= form_with model: @product, local: true do |form| %>
        <div class="row border" style="height: 15%; background-color: #d9d9d9;">
          <div class="col">
            <p class="text-right" style="font-size: 6vh;">
              <%= form.label :name %>
            </p>
          </div>

          <div class="col-10">
            <p class="h-100">
              <%= form.text_field :name, :class => 'w-100 h-100 mh-100', :style => 'font-size: 6vh;' %>
            </p>
          </div>
        </div>

        <div class="row border" style="height: 15%; background-color: #d9d9d9;">
          <div class="col">
            <p class="text-right" style="font-size: 6vh;">
              <%= form.label :dimension %>
            </p>
          </div>

          <div class="col-10">
            <p class="h-100">
              <%= form.text_field :dimension, :class => 'w-100 h-100 mh-100', :style => 'font-size: 6vh;' %>
            </p>
          </div>
        </div>

        <div class="row border" style="height: 15%; background-color: #d9d9d9;">
          <div class="col">
            <p class="text-right" style="font-size: 6vh;">
              <%= form.label :price %>
            </p>
          </div>

          <div class="col-10">
            <p class="h-100">
              <%= form.text_field :price, :class => 'w-100 h-100 mh-100', :style => 'font-size: 6vh;' %>
            </p>
         </div>
        </div>

        <div class="row border" style="height: 15%; background-color: #20c997;">
          <div class="col">
            <%= form.submit 'Create', :class => 'btn btn-primary btn-block h-100', :style => 'font-size: 8vh; opacity: .7; background-color: #008CBA;' %>
          </div>
        </div>
      <% end %>

      <div class="row border" style="height: 10%; background-color: #20c997">
        <div class="col mh-100 justify-content-center align-self-center">
          <p class="text-center" style="font-size: 5vh;">Trademark Information - &#169; esoterickeys</p>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="container-fluid main_container d-flex" style="min-height: 100vh;">
  <div class="row border flex-fill">
    <div class="col h-100">

      <div class="row border" style="height: 25%; background-color: #20c997">
        <div class="col mh-100 justify-content-center align-self-center">
          <p class="mh-100 text-center" style="font-size: 10vh;"><%= @product.name %></p>
        </div>
      </div>

      <div class="row border" style="height: 15%; background-color: #20c997;">
        <div class="col">
          <%= link_to '<button type="button" class="btn btn-primary btn-block h-100" style="font-size: 8vh; opacity: .7; background-color: #008CBA;">Back</button>'.html_safe, controller:  'products' %>
        </div>
      </div>

      <div class="row border" style="height: 15%; background-color: #d9d9d9;">
        <div class="col">
          <p class="text-right" style="font-size: 5vh;">
            <strong>Name</strong>
          </p>
        </div>

        <div class="col-10">
          <p class="w-100 h-100 mh-100" style="font-size: 6vh;">
            <%= @product.name %>
          </p>
        </div>
      </div>

      <div class="row border" style="height: 15%; background-color: #d9d9d9;">
        <div class="col">
          <p class="text-right" style="font-size: 5vh;">
            <strong>Dimension</strong>
          </p>
        </div>

        <div class="col-10">
          <p class="w-100 h-100 mh-100" style="font-size: 6vh;">
            <%= @product.dimension %>
          </p>
        </div>
      </div>

      <div class="row border" style="height: 15%; background-color: #d9d9d9;">
        <div class="col">
          <p class="text-right" style="font-size: 5vh;">
            <strong>Price</strong>
          </p>
        </div>

        <div class="col-10">
          <p class="w-100 h-100 mh-100" style="font-size: 6vh;">
            <%= @product.price %>
          </p>
        </div>
      </div>

      <div class="row border" style="height: 10%; background-color: #20c997">
        <div class="col mh-100 justify-content-center align-self-center">
          <p class="text-center" style="font-size: 5vh;">Trademark Information - &#169; esoterickeys</p>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/splash/index.html.erb
<div class="container-fluid main_container d-flex" style="min-height: 100vh;">
  <div class="row border flex-fill">
    <div class="col h-100">

      <div class="row border" style="height: 30%; background-color: #20c997">
        <div class="col mh-100 justify-content-center align-self-center">
          <p class="mh-100 text-center" style="font-size: 10vh;">Company Name</p>
        </div>
      </div>

      <div class="row border" style="height: 20%; background-color: #20c997;">
        <div class="col">
          <%= link_to '<button type="button" class="btn btn-primary btn-block h-100" style="font-size: 8vh; opacity: .7; background-color: #008CBA;">About</button>'.html_safe, controller: 'about' %>
        </div>
      </div>

      <div class="row bordert" style="height: 20%; background-color: #20c997;">
        <div class="col">
          <%= link_to '<button type="button" class="btn btn-primary btn-block h-100" style="font-size: 8vh; opacity: .7; background-color: #008CBA;">Products</button>'.html_safe, controller: 'products' %>
        </div>
      </div>

      <div class="row border" style="height: 20%; background-color: #20c997;">
        <div class="col">
          <%= link_to '<button type="button" class="btn btn-primary btn-block h-100" style="font-size: 8vh; opacity: .7; background-color: #008CBA;">Contact</button>'.html_safe, controller: 'contact' %>
        </div>
      </div>

      <div class="row border" style="height: 10%; background-color: #20c997">
        <div class="col mh-100 justify-content-center align-self-center">
            <p class="text-center" style="font-size: 5vh;">Trademark Information - &#169; esoterickeys</p>
        </div>
      </div>

    </div>
  </div>
</div>